#!/bin/bash
set -ex

ls -lah /usr/local/src/
cd /usr/local/src/vips-%VERSION%

CXXFLAGS="-D_GLIBCXX_USE_CXX11_ABI=0" ./configure \
    --disable-debug \
    --disable-static \
    --disable-introspection \
    --disable-dependency-tracking \
    --without-python \
    --without-orc \
    --without-fftw

make
make install

echo "Installed libvips $( PKG_CONFIG_PATH=$PKG_CONFIG_PATH:/usr/local/lib/pkgconfig:/usr/lib/pkgconfig pkg-config --modversion vips )"
ldconfig
